# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\JetBrains\CLion 2016.3.4\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\JetBrains\CLion 2016.3.4\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Studies\Data Structures\hwlast\wet\pp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Studies\Data Structures\hwlast\wet\pp\cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\JetBrains\CLion 2016.3.4\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files (x86)\JetBrains\CLion 2016.3.4\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Studies\Data Structures\hwlast\wet\pp\cmake-build-debug\CMakeFiles" "C:\Studies\Data Structures\hwlast\wet\pp\cmake-build-debug\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Studies\Data Structures\hwlast\wet\pp\cmake-build-debug\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pp

# Build rule for target.
pp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 pp
.PHONY : pp

# fast build rule for target.
pp/fast:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/build
.PHONY : pp/fast

HoursAndTrees.obj: HoursAndTrees.cpp.obj

.PHONY : HoursAndTrees.obj

# target to build an object file
HoursAndTrees.cpp.obj:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/HoursAndTrees.cpp.obj
.PHONY : HoursAndTrees.cpp.obj

HoursAndTrees.i: HoursAndTrees.cpp.i

.PHONY : HoursAndTrees.i

# target to preprocess a source file
HoursAndTrees.cpp.i:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/HoursAndTrees.cpp.i
.PHONY : HoursAndTrees.cpp.i

HoursAndTrees.s: HoursAndTrees.cpp.s

.PHONY : HoursAndTrees.s

# target to generate assembly for a file
HoursAndTrees.cpp.s:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/HoursAndTrees.cpp.s
.PHONY : HoursAndTrees.cpp.s

library.obj: library.cpp.obj

.PHONY : library.obj

# target to build an object file
library.cpp.obj:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/library.cpp.obj
.PHONY : library.cpp.obj

library.i: library.cpp.i

.PHONY : library.i

# target to preprocess a source file
library.cpp.i:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/library.cpp.i
.PHONY : library.cpp.i

library.s: library.cpp.s

.PHONY : library.s

# target to generate assembly for a file
library.cpp.s:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/library.cpp.s
.PHONY : library.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/main.cpp.s
.PHONY : main.cpp.s

scheduleMatrix.obj: scheduleMatrix.cpp.obj

.PHONY : scheduleMatrix.obj

# target to build an object file
scheduleMatrix.cpp.obj:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/scheduleMatrix.cpp.obj
.PHONY : scheduleMatrix.cpp.obj

scheduleMatrix.i: scheduleMatrix.cpp.i

.PHONY : scheduleMatrix.i

# target to preprocess a source file
scheduleMatrix.cpp.i:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/scheduleMatrix.cpp.i
.PHONY : scheduleMatrix.cpp.i

scheduleMatrix.s: scheduleMatrix.cpp.s

.PHONY : scheduleMatrix.s

# target to generate assembly for a file
scheduleMatrix.cpp.s:
	$(MAKE) -f CMakeFiles\pp.dir\build.make CMakeFiles/pp.dir/scheduleMatrix.cpp.s
.PHONY : scheduleMatrix.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... rebuild_cache
	@echo ... pp
	@echo ... edit_cache
	@echo ... HoursAndTrees.obj
	@echo ... HoursAndTrees.i
	@echo ... HoursAndTrees.s
	@echo ... library.obj
	@echo ... library.i
	@echo ... library.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... scheduleMatrix.obj
	@echo ... scheduleMatrix.i
	@echo ... scheduleMatrix.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

